### ISSUE TITLE
adding base/bin to path in setpaths.sh/csh

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#145]
Are there any concerns adding the ```base/bin``` directory to $PATH?
I suspect the answer is 'no', but wanted to ask the question anyway.

(We need to be able to access the h5* executables of the installed hdf5 library, instead of ancient ones that may be available from the system or elsewhere.)

**Comment by graeme-winter** [comment]
+1 I would very much like this

**Comment by Oeffner** [comment]
On Windows the HDF5 programs live in base\HDF5-1.8.16\bin

**Comment by bkpoon** [comment]
Would making dispatchers to the h5 executables in build/bin work? It would be similar to how build/bin/python is done (for development builds, not builds from installers).

The CCTBX runtime environment tries to be as least disruptive as possible, so the scripts for setting up the environment generally just adds build/bin to $PATH and maybe a bunch of variables for CCTBX locations (setpaths_all.sh).

If we add base/bin to $PATH, everything in base/bin would take precedence, which on Linux would include a bunch of GUI stuff that can be problematic for the user. Also, since the h5 executables dynamically link to hdf5.so in base/lib, we would also have to prepend base/lib to $LD_LIBRARY_PATH, which would also add a bunch of other libraries that would take precedence and potentially cause unintended consequences. The dispatchers avoid these issues by only setting up the library paths in its own shell process.

Lastly, there are methods of configuring CCTBX without a base directory (e.g. xfel with psana), so dispatchers would avoid that issue as well (or add a check for base before prepending $PATH).

**Comment by Anthchirp** [comment]
What do you mean by "bunch of GUI stuff"?
Point about libraries well received, some redirectors clearly needed.
Last bit not really a concern I think, adding a non-existing path to $PATH is harmless.

**Comment by Oeffner** [comment]
base packages gtk, xrender, png and such like is a bunch of GUI stuff I think

**Comment by bkpoon** [comment]
Also, fontconfig, cairo, gdk, wxwidgets, and glib have binaries in base/bin. These dependencies are also built with the expectation that they are only used for CCTBX programs, not as a general replacement. For example, there is no JPEG support since that option is explicitly disabled for gdk (otherwise, we would have to provide libjpeg as a dependency).

The last time I updated the different GUI dependencies, they seemed really picky about which versions are compatible with each other, and I found a combination that was pretty compatible with multiple version of CentOS and Ubuntu. When Ubuntu 18.04 LTS comes out in April, I guess we'll have to do another update to make sure things work (#85).

I just tested Firefox from the command-line with base/bin in $PATH and base/lib:base/lib64 in $LD_LIBRARY_PATH and I get a bunch of warnings that don't normally appear. My concern with modifying PATH and LD_LIBRARY_PATH is these issues with non-CCTBX programs that cannot be easily tested.

However, I'm also looking into making a build where we provide libgcc and libstdc++ (to provide C++11 support to older platforms). In this case, it would make sense to adapt conda since they provide libgcc and libstdc++ (gcc 7.2) and maintenance of dependencies can be simplified. And since the conda environment puts its bin directory first in the $PATH, this should also solve your issue if you use the conda version of hdf5 (or manually build our own in a separate conda channel).

**Comment by ndevenish** [comment]
FWIW, I *always* add `base/bin` anyway, because I can't access extra tools installed from `pip` without it. Otherwise, I don't think adding the base `lib` dir with `LD_LIBRARY_PATH` is necessary - at least on my installations, the HDF5 tools have a proper `RPATH` set up, and if moving them around we should ensure that stays valid (I also recently noticed incorrect RPATH's on much of our built libraries, but that's a different, longer-term issue).

That said, I'd much rather add dispatchers in `build/bin`, because we should discourage excessive coupling to base. But how necessary is this? For debugging? Because perhaps it'd be more appropriate to just add the `base/bin` to `setpaths_debug` or `setpaths_all`, assuming they don't already.

@bkpoon It's good to hear you're looking at bundling libstdc++. It's something on our list, but we've never got around to seriously looking at it yet.

**Comment by Anthchirp** [comment]
@ndevenish so you should now have dispatchers for python extra tools such as ```pip``` in build/bin. And all the other commands that come from console_scripts. None of these should interfere with anything.

I'm not sure yet what to do about the h5 stuff and other base executables. Looks like the best option is a a generation of dispatchers from a whitelist.

**Comment by bkpoon** [comment]
You may want to add a prefix to the dispatcher names so that they are named libtbx.pip or dials.h5stat or cctbx.python. Developer environments may be well-behaved, but user environments tend to be heterogeneous. If there is a ```pip``` in build/bin, a CCTBX program may not get that one since build/bin may not be the first location in $PATH with ```pip``` on a users machine. Prefixing the command name is not a guaranteed fix, but it should lower the probability of failure.

Also, if this is specifically for developer use, maybe treat these dispatchers the same way ```python``` is handled where that dispatcher does not exist for user installations.

**Comment by bkpoon** [comment]
@ndevenish The ```RPATH``` issue can be looked the next time the GUI dependencies are updated. But my understanding is that because we were using dispatchers which set ```LD_LIBRARY_PATH```, that was sufficient. And also the original design was to not interfere at all with the user's environment. This is something that can be re-evaluated, especially if we move to ```conda``` and conda environments.

**Comment by Anthchirp** [comment]
Entirely sensible suggestion. We just discussed this here, and will go with adding a ```libtbx.``` prefix to all things.

**Comment by Anthchirp** [comment]
done
