### ISSUE TITLE
Fresh bootstrap Python on OS X does not allow pip install jupyter because of dependencies

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#157]
Looks like it is somehow locking in the OS X 10.4 ABI which is prehistoric: is due to dependency on scandir...

```
Graemes-MBP-6:scandir-1.7 graeme$ libtbx.python
Python 2.7.14 (default, Mar 27 2018, 12:43:09) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

```
Graemes-MBP-6:scandir-1.7 graeme$ libtbx.python setup.py build
running build
running build_py
running build_ext
building '_scandir' extension
gcc -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/graeme/svn/cctbx/base/Python.framework/Versions/2.7/include/python2.7 -c _scandir.c -o build/temp.macosx-10.4-x86_64-2.7/_scandir.o
_scandir.c:625:24: error: no member named 'st_birthtimespec' in 'struct stat'
      bsec = (long)st->st_birthtime;
                   ~~  ^
/usr/include/sys/stat.h:234:22: note: expanded from macro 'st_birthtime'
#define st_birthtime st_birthtimespec.tv_sec
                     ^
_scandir.c:627:19: error: no member named 'st_birthtimespec' in 'struct stat'
      bnsec = st->st_birthtimespec.tv_nsec;
              ~~  ^
2 errors generated.
error: command 'gcc' failed with exit status 1
```

This is 10.13...

**Comment by graeme-winter** [comment]
System python happy bunny is:

```
Graemes-MBP-6:scandir-1.7 graeme$ /usr/bin/python setup.py build
running build
running build_py
creating build/lib.macosx-10.13-intel-2.7
copying scandir.py -> build/lib.macosx-10.13-intel-2.7
running build_ext
building '_scandir' extension
creating build/temp.macosx-10.13-intel-2.7
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _scandir.c -o build/temp.macosx-10.13-intel-2.7/_scandir.o
cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.13-intel-2.7/_scandir.o -o build/lib.macosx-10.13-intel-2.7/_scandir.so

```

**Comment by ndevenish** [comment]
Wasn't there a patch a while ago where we forced MACOSX_DEPLOYMENT_TARGET unnecessarily or something?

**Comment by graeme-winter** [comment]
@bkpoon this looks like something you would know about.

**Comment by graeme-winter** [comment]
@ndevenish I see

Log:
Remove macOS deployment target; add codebase for ci scheduler

```
@@ -196,7 +197,7 @@
    kwargs['timeout'] = 60*60*2 # 2 hours
    if 'workdir' in kwargs:
      kwargs['workdir'] = self.opjoin(*kwargs['workdir'])
-    default_env = {"MACOSX_DEPLOYMENT_TARGET" : "10.6"}
+    default_env = dict()
    if "env" in kwargs:
      # Use Property of same env. var.
      for key, item in kwargs["env"].items():
@@ -767,13 +768,13 @@

##### Slaves #####
```

**Comment by Anthchirp** [comment]
That commit is unrelated, this is from the buildbot configuration and only affects buildbot. Base builds run exclusively from cctbx_project, so if the cause is in the base build then that is where the problem lies.

**Comment by bkpoon** [comment]
This looks like a more complicated issue since "10.4" is hard-coded into the Python source tree. A brief test with the `--enable-universalsdk` didn't seem to work, as well has defining `CC`, `CPP`, and `CXX` environment variables. Also, Apple's Python is non-standard (their `setuptools` version is 1.1.6, whereas the standard version is up to 39.0.1), so a fix will probably involve patching the Python source.

The conda version of python also works, but they build against the 10.6 SDK, which is odd since they recommend 10.9 (https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html) for building packages.

I'll have more time next week to look into this.

@ndevenish If you're referring to #87, third-party dependencies tend to do things in the `configure` step that makes things behave weirdly. If you have a better set of flags that compile with Xcode 8 and 9 (Xcode 7 can probably deprecated because of the security changes to various websites) and works on 10.7 and later (realistically 10.9 and later), we can incorporate them. Also, I'm currently evaluating conda as a replacement for rolling our own dependencies. Some compilation will probably be still required, so better compilation flags would apply to conda as well.

**Comment by graeme-winter** [comment]
@bkpoon fair point - looking now at straight configure / make on downloaded python 2.7.13 tarball, looks like it was compiled against 10.4 ABI

**Comment by graeme-winter** [comment]
Since this is a fundamental issue with Python, not just the bootstrap script, closing.

**Comment by ndevenish** [comment]
I’m pretty sure it’s the fiddling around we do with build flags, causing an ABI conflict somewhere. Python doesn’t need higher than 10.4 compatibility which is why they set it at that level.

It worked, with the exact same version of python, with base a couple of months ago.

**Comment by Anthchirp** [comment]
Should be fairly easy to test?
Download python, compile python, pip install, see what happens.
Compile python with flags as used by bootstrap, pip install, see if anything different happens.

**Comment by bkpoon** [comment]
Not quite, you would want to test if a C++11 build of CCTBX programs that call C++ code will work with that python. Rosetta requires C++11 and there is an ABI difference between libc++ and libstdc++, which was causing issues with users.

The conda folks have worked on this and I'm taking a look at what they did to get things working. 

https://github.com/conda-forge/conda-forge.github.io/issues/183
