### ISSUE TITLE
Python3 conversion of boost_adaptbx C++

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#165]
```bootstrap.py``` now has a ```--python3``` parameter to build a Python3 base. With today's patches this now proceeds up to the ```build``` step, wherein:

```
In file included from (..)/cctbx_project/boost_adaptbx/meta_ext.cpp:15:0:
(..)/cctbx_project/boost_adaptbx/python_streambuf.h: In member function ‘virtual boost_adaptbx::python::streambuf::int_type boost_adaptbx::python::streambuf::underflow()’:
(..)/cctbx_project/boost_adaptbx/python_streambuf.h:201:65: error: ‘PyString_AsStringAndSize’ was not declared in this scope
                                    &read_buffer_data, &py_n_read) == -1) {
```

So this is now the point where someone with C++ knowledge who is not me needs to figure out how to make this whole boost+python thing work with the python2 vs python3 string and bytes and unicode ~mess~ model.

This link may be helpful: https://docs.python.org/3/howto/cporting.html

Good luck.

**Comment by Anthchirp** [comment]
@ndevenish found this http://py3c.readthedocs.io/en/latest/ which also looks useful.

**Comment by phyy-nx** [comment]
Working branch:
https://github.com/cctbx/cctbx_project/tree/cpp_python3

Some initial work done with @bkpoon.  More to go.

**Comment by bkpoon** [comment]
Hi Markus,

Let's hold off on converting tests to pytest until there's been a policy
discussion among the PIs. At the latest, we can discuss it at the Gordon
Research Conference in July since a bunch of PIs will be there.

--
Billy K. Poon
Research Scientist, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
1 Cyclotron Road, M/S 33R0345
Berkeley, CA 94720
Tel: (510) 486-5709
Fax: (510) 486-5909
Web: https://phenix-online.org

**Comment by graeme-winter** [comment]
@bkpoon etc please could we move testing related stuff to a new ticket so we don't end up discussing testing in each other ticket?

**Comment by graeme-winter** [comment]
To clarify: I mean pytest-ing 😄since I know we need to have good test coverage in here. Will mean we can close before August.

**Comment by Anthchirp** [comment]
nothing further expected here
