### ISSUE TITLE
In bootstrap build, enable thread-safety for hdf5 library

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#176]
At the moment the default is 

```

  --enable-threadsafe     Enable thread-safe capability. Not compatible with
                          the high-level library, Fortran, or C++ wrappers.
                          [default=no]
```

because thread safe code is bad, right? But if (threading) in e.g. our own implementation of a neggia plugin ends badly with SEGV => can we make this --enable-threadsafe=yes please?

**Comment by graeme-winter** [comment]
@jmp1985 @phyy-nx two obvious people who probably hold an opinion here

**Comment by phyy-nx** [comment]
What does "Not compatible with the high-level library, Fortran, or C++ wrappers" mean?  If it refers to h5py, then I'd be worried.

We have had issues with crashes and multiprocessing with hdf5 ourselves though.  Maybe @asmit3 can describe the symptoms he saw?

**Comment by asmit3** [comment]
From the EUXFEL beamtime in October 2017, while processing a single NeXus file with multiple images in it using stills_process.py (and using python multiprocessing), I got the following message for random images in the NeXus file:

**Error spotfinding XFEL2012-r0071-c00_master_00156 dxtbx Internal Error: /home/asmit/software/cctbx.xfel/modules/cctbx_project/dxtbx/format/boost_python/nexus_ext.cc(85): DXTBX_ASSERT(status2 >= 0) failure.**

When I ran the code multiple times on the same file (with the same parameters), I was unable to reproduce the number of images processed. 

The solution was to switch to MPI. I didn't see any dxtbx errors or crashes and was able to reproduce the number of images processed. There probably is an issue with multiple reads of the h5 file with python multiprocessing which caused these problems. @phyy-nx and I have not looked at it since.

To comment on the change proposed, at the very least, h5py will not support thread-safety (it uses C++ header files). Although workarounds probably exist, the HDF5 website specifically recommends not using these. See this link - 
https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access

**Comment by ndevenish** [comment]
> because thread safe code is bad, right?

I assume this was a joke; but thread safe code probably comes with lots of trade-offs, especially in performance.

> What does "Not compatible with the high-level library, Fortran, or C++ wrappers" mean? If it refers to h5py, then I'd be worried.

I'm pretty sure that h5py wraps the C-API, not the C++ API, so it *would* get the internal API safety changes, but you'd need also to be sure that h5py itself didn't add anything. (FWIW h5py [claims](http://docs.h5py.org/en/latest/whatsnew/2.4.html#thread-safety-improvements) to be thread-safe from 2.4). 

High-level means the convenience [HL](https://support.hdfgroup.org/HDF5/doc/HL/) interface - I don't think we use it but I have seen third party CCTBX modules that use it. I've only ever seen the HDF5 C API used in our C++ code, but I could be wrong on that too.

Although turning it on shouldn't break anything, I'd probably want to see performance measurements to verify that it doesn't e.g. grind our HDF5 reading to a halt.

**Comment by graeme-winter** [comment]
Also needs

```
--disable-hl 
```

**Comment by graeme-winter** [comment]
Or, alternatively

```
--enable-unsupported
```

Yes, you can kill my kittens

**Comment by graeme-winter** [comment]
In my use case the latter was the thing I needed - turns out the high level API was used somewhere.

**Comment by phyy-nx** [comment]
Hi Graeme, does Nick Devenish's comment still apply?

"Although turning it on shouldn't break anything, I'd probably want to see
performance measurements to verify that it doesn't e.g. grind our HDF5
reading to a halt."

Also I'm still concerned about this statement from the link Asmit posted:
https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access

"Can you run Parallel HDF5 and the thread-safe feature together ?
By default, you cannot build Parallel HDF5 with the thread-safe feature.
You will receive a configure error if you try this combination.  A check
was added to the configure to disallow this, as it is not tested and may
fail.

However, the --enable-unsupported configure option enables you to get
around this check at your own risk. (You can actually view the configure
file to see where the check is made.) If the build completes properly and
the tests pass, then the installation should be okay."

It seems like this feature is so untested that the HDF group is worried
about it.  If we enable this flag does MPI reading of Eiger files in
dials.stills_process still work?

Thanks,
-Aaron

**Comment by biochem-fan** [comment]
We also use multi-image HDF5 files at SACLA. Indeed parallel processing in `dials.stills_process` caused some problems. As of Oct 2015, deep copying of an instance of a format class which contains open h5py handles led to crash. So, my dxtbx class (`dxtbx/format/FormatHDF5SaclaMPCCD.py`) opens & closes h5py handles in every method! Of course this is bad for performance, but other computations were rate limiting. I don't know if this still applies now.

**Comment by phyy-nx** [comment]
Thanks.  Graeme, if you have an mpi enabled build, you can use this to test
MPI and SACLA:

cd $modules/dials/test/command_line
libtbx.pytest test_stills_process.py::test_sacla_h5[True]

Without MPI this test is skipped.  I just put in a fix to the MPI test and
it now correctly faster using 4 processors.

**Comment by graeme-winter** [comment]
Worked around the problem for my own use case - will close, please reopen if necessary for other use cases.
