### ISSUE TITLE
DEPTH_BUFFER needed in wx_viewer GlCanvas init

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#220]
in cctbx multiplicity viewer get some weird things going on - on OS X noticed this and with help from @ndevenish identified that `kw["attribList"].extend([wx.glcanvas.WX_GL_DEPTH_SIZE, 24])` needed i.e. 

```python
     if hasattr(wx.glcanvas, 'WX_GL_RGBA'):
       kw['attribList'].append(wx.glcanvas.WX_GL_RGBA) # required on Windows
 
     kw["attribList"].extend([wx.glcanvas.WX_GL_DEPTH_SIZE, 24]) # how to make this portable?

     if hasattr(wx.glcanvas, 'WX_GL_DOUBLEBUFFER'):
       try:
         if self.IsDisplaySupported(wx.glcanvas.WX_GL_DOUBLEBUFFER):
```

=> please can we work out a way to make something like this happen?

**Comment by ndevenish** [comment]
I noticed this a while ago whilst experimenting with the reciprocal lattice viewer and OpenGL; on some platforms (e.g. RHEL6) it seems that a depth buffer is allocated by default; on others (e.g. OSX) it seems that it isn't. This just never normally became noticed because none of the regular DIALS tools uses the depth buffer. The problem is even present in the WXPython tutorials, so not that much of a surprise.

My assumption is that a solution would look something like:

```python
    # Find the highest reasonable depth buffer this display supports
    for buffer_depth in [24,16,8,4]:
      if self.IsDisplaySupported([wx.glcanvas.WX_GL_DEPTH_SIZE, buffer_depth]):
        kw['attriblist'].extend([wx.glcanvas.WX_GL_DEPTH_SIZE, buffer_depth])
        break
```

**Comment by graeme-winter** [comment]
Nick, this sounds like a sensible solution, thank you 👍
