### ISSUE TITLE
Replace PIL with Pillow

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#24]
As mentioned in mail on 2017-04-01 the [PIL (Python Image Library) is abandonware](https://en.wikipedia.org/wiki/Python_Imaging_Library), and we should move to the actively maintained fork of the PIL-replacement library, [Pillow](http://pillow.readthedocs.io/en/latest/).

Any concerns regarding this?

**Comment by Anthchirp** [comment]
patch for this now under test.

**Comment by phyy-nx** [comment]
Hi, PIL is still being installed.  Will it need to be removed?

**Comment by Anthchirp** [comment]
What do you mean "is still being installed"? It comes as default but there is no explicit step, yes?
The installation of Pillow removes and replaces PIL.

**Comment by bkpoon** [comment]
PIL is installed as the "imaging" package. I just built a new base directory and when I run `libtbx.python -m pip list`, PIL (1.1.7) shows up in addition to Pillow. So I guess the easy fix is to just replace "imaging" with "pillow" in install_base_packages.py. That should also preserve the order of packages being installed so that any dependencies are preserved.

I remember trying to replace PIL with Pillow a while ago, but I was getting warnings/errors about `fromstring` and `frombytes` functions, so I never pushed the change. I guess `fromstring` is deprecated (probably because of the change in Python 3 of `str` to `bytes` for bytestrings and `str` only being used for text/Unicode strings). (https://github.com/python-pillow/Pillow/issues/63). I do see a few calls to `PIL.Image.fromstring` in cctbx and dials, so should we just update all references of `PIL.Image.fromstring` to `PIL.Image.frombytes`? I'm not familiar enough with Pillow or the code calling Pillow functions.

**Comment by Anthchirp** [comment]
I see, I thought PIL was installed as part of python. I'll patch this in a minute. The nightly bootstrap run here did exactly as planned and installed PIL, then replaced it as part of the pillow install. Easy way to test for Pillow btw is 
```
dials.python -c "import PIL; print PIL.__version__"
```
which fails on PIL with an ```AttributeError```.

**Comment by Anthchirp** [comment]
Just tested ```labelit.png```/```iotbx/command_line/detector_image_as_png.py``` and that seems to work fine. It uses this pattern:
```python
  try:
    self.imageout = Image.fromstring("RGB",
                         (flex_img.ex_size2(), flex_img.ex_size1()),
                         data_string)
  except Exception:
    self.imageout = Image.frombytes("RGB",
                         (flex_img.ex_size2(), flex_img.ex_size1()),
                         data_string)
```
I think updating all references ```fromstring``` to ```frombytes``` is the appropriate course of action.

**Comment by Anthchirp** [comment]
I've done some changes in cctbx, dials, dials_regression, labelit, labelit_regression. Obviously can't guarantee I got them all.

One place I did not change was ```labelit/bundle/install_python_here.csh```, which contains an installer and test for the old PIL library. Changing this is a bit more involved.
