### ISSUE TITLE
Disable user's site directory

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#37]
Users with a per-user site packages directory can fail install_base_packages in the verification step because their site packages directory will take precedence over the base folder being constructed.

From @graeme-winter:

"https://www.python.org/dev/peps/pep-0370/

The user site directory can be suppressed with a new option -s or the environment variable PYTHONNOUSERSITE . The feature can be disabled globally by setting site.ENABLE_USER_SITE to the value False . It must be set by editing site.py . It can't be altered in sitecustomize.py or later."

From @dagewa, we can do this by adding '-S' to the call at line 465 of install_base_packages.py (inside the verify_python_module function).

-s and -S seem to do different things.  Which is correct?

**Comment by Anthchirp** [comment]
-s is correct.

-S inhibits the mechanism used in dials/dials#308, but will not have an effect on the per-user modules

**Comment by bkpoon** [comment]
The fix is in 2 parts:

1) During installation, the PYTHONNOUSERSITE environment variable is set so that the per user site-packages directory is not used for anything. Installation of some Python packages may try to import other modules. For example, some Python package for HDF5 fails because it tries to import numpy.
2) After installation, PYTHONPATH in the dispatchers is changed so that the CCTBX site-packages directory is added. This puts our site-packages directory in front of the per user site-packages directory.

These changes should allow users to install packages in the standard per user site-packages location and have those work with our Python. In the event of duplicated Python modules, our versions will take precedence.

**Comment by bkpoon** [comment]
No new problems seem to have popped up, so I'm closing this issue.
