### ISSUE TITLE
Adding anaconda to `LD_LIBRARY_PATH` will output `libreadline.so.7` warnings on CLE7

### ISSUE THREAD

**Issue by JBlaschke** [cctbx/cctbx_project#442]
As far as I can tell, all the scripts in `build/bin` contain bits like this:
```
if [ -n "$LD_LIBRARY_PATH" ]; then
  LD_LIBRARY_PATH="$LIBTBX_BUILD/lib:$LIBTBX_BUILD/../../../../conda/miniconda3/envs/xtc_base/lib:$LD_LIBRARY_PATH"
  export LD_LIBRARY_PATH
else
  LD_LIBRARY_PATH="$LIBTBX_BUILD/lib:$LIBTBX_BUILD/../../../../conda/miniconda3/envs/xtc_base/lib"
  export LD_LIBRARY_PATH
fi
```
Adding the anaconda environment libs directory (in this case `$LIBTBX_BUILD/../../../../conda/miniconda3/envs/xtc_base/lib`) to the `LD_LIBRARY_PATH` is probably meant well, but it is not necessary (anaconda links with `rpath`). Worse still, this causes a version conflict with CLE7's `readline` on NERSC's Cori system.

Hence, building cctbx on cori means your stderr is full of warnings like:
```
/bin/sh: /global/u1/b/blaschke/ExaFEL/NESAP/CCTBX/deploy/pipelines/xtc_process/cctbx/build/../../../../conda/miniconda3/envs/xtc_base/lib/libreadline.so.7: no version information available (required by /bin/sh)
```

## Solution: 

Can we change the way these wrappers are generated, to not add conda's lib dir to `LD_LIBRARY_PATH`?

Alternatively, can we add some controls to `bootstrap.py` to let the user select whether or not to add conda/lib to `LD_LIBRARY_PATH`?

**Comment by bkpoon** [comment]
I added the conda library path since some of the extensions that we build may link against those libraries (e.g. `numpy`), but I can double check. Currently, the process for creating installers will adjust the `rpath` of our libraries and extensions, so you can try running that step and removing the `LD_LIBRARY_PATH` lines from the dispatchers.

I have a function for generating dispatchers that do not set any environment variables. It's still under testing for building conda packages, but I can make that available in a branch.

**Comment by JBlaschke** [comment]
@bkpoon Yes if extensions are linking against conda dependencies, without using `rpath` then this is the way to go. This would requires a bit of a deeper dive into how the extensions are built and linked.

I suggest that we explore these solutions (dispatcher generators that don't set env variables, or cori-specific packages) on Cori (once she's up again).  This approach sounds better than building a script to remove conda from the `LD_LIBRART_PATHS` in all the dispatcher scripts.

**Comment by JBlaschke** [comment]
Discussion with @bkpoon resolved this issue
