### ISSUE TITLE
wxtbx utils: Gtk-CRITICAL... assertion 'width >= -1' failed messages

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#46]
On Ubuntu at least, `dials.reciprocal_lattice_viewer` emits a number of annoying messages to the terminal when it starts up:

```
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

(reciprocal_lattice_viewer.py:28128): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(reciprocal_lattice_viewer.py:28128): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(reciprocal_lattice_viewer.py:28128): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(reciprocal_lattice_viewer.py:28128): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(reciprocal_lattice_viewer.py:28128): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed

(reciprocal_lattice_viewer.py:28128): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'width >= -1' failed
```

I have found that the last 6 of these messages go away with this simple patch:
```
$ git diff
diff --git a/wxtbx/utils.py b/wxtbx/utils.py
index 17e1bd7..0cb2139 100644
--- a/wxtbx/utils.py
+++ b/wxtbx/utils.py
@@ -106,6 +106,7 @@ class SettingsPanel (wx.Panel, SettingsToolBase) :
     self.panel_sizer = wx.BoxSizer(wx.VERTICAL)
     self.SetSizer(self.panel_sizer)
     self.add_controls()
+    self.panel_sizer.SetSizeHints(self)
     self.panel_sizer.Layout()
 
 def bold_text (parent, label) :

```
Now, I don't pretend to understand what this line actually does or what effect it has on other projects. I discovered this by trial and error. Could somebody with a better knowledge of wxPython comment here?

**Comment by bkpoon** [comment]
Hi David,

For the failed module messages, it's a quirk from building gtk that I have not found a solution yet. The canberra module is related to modifying sound settings, which we don't really need, but I have not found the configure setting to turn it off. For the other modules, I don't see those, but I'm guessing you compiled the base dependencies on your Ubuntu system and the gtk build picked up some additional packages. I think the "overlay-scrollbar" and "unity-gtk-module" is specific to the Unity GUI in Ubuntu and the scollbars that pop up when you're near and edge. It's also not clear why those packages are not found since I suspect they are already installed.

For the Gtk-CRITICAL messages, the basic idea is that only the top-level window calls the SetSizeHints function. The online docs (https://wxpython.org/onlinedocs.php) for wxPython has some programming guides. You may need to "allow unsafe scripts to run" in Chrome to see the page.

The messages pop up because Layout is called in the constructor, which tries place things without having any size hints. Layout should be called at the end of the top-level window/frame constructor once the window/frame is composed or when a change occurs that may change the size of some widget, in which case, Layout should be called by some event.

I think a better fix would be to remove the Layout call in the SettingsPanel constructor and to call SetSizerAndFit in the ReciprocalLatticeViewer constructor. The SetSizerAndFit function is just a shortcut for calling SetSizer and SetSizeHints. I also added a SetMinSize function call so that when you try to resize the window, it won't get smaller than the SettingsPanel object. I copied diffs below.

```diff
diff --git a/wxtbx/utils.py b/wxtbx/utils.py
index 17e1bd724..a709e38be 100644
--- a/wxtbx/utils.py
+++ b/wxtbx/utils.py
@@ -106,7 +106,7 @@ class SettingsPanel (wx.Panel, SettingsToolBase) :
     self.panel_sizer = wx.BoxSizer(wx.VERTICAL)
     self.SetSizer(self.panel_sizer)
     self.add_controls()
-    self.panel_sizer.Layout()

 def bold_text (parent, label) :
   txt = wx.StaticText(parent, label=label)
```

```diff
diff --git a/command_line/reciprocal_lattice_viewer.py b/command_line/reciprocal_lattice_viewer.py
index 4527ef76..9ddd4471 100644
--- a/command_line/reciprocal_lattice_viewer.py
+++ b/command_line/reciprocal_lattice_viewer.py
@@ -263,8 +263,7 @@ def __init__(self, *args, **kwds):
     self.sizer.Add(self.settings_panel, 0, wx.EXPAND)
     self.create_viewer_panel()
     self.sizer.Add(self.viewer, 1, wx.EXPAND|wx.ALL)
-    self.SetSizer(self.sizer)
-    self.sizer.SetSizeHints(self)
+    self.SetSizerAndFit(self.sizer)
+    self.SetMinSize(self.settings_panel.GetSize())
     self.Bind(wx.EVT_CLOSE, self.OnClose, self)
     self.Bind(wx.EVT_WINDOW_DESTROY, self.OnDestroy, self)
     self.Bind(wx.EVT_ACTIVATE, self.OnActive)
```

**Comment by dagewa** [comment]
Hi Billy, thanks for the detailed explanation and much improved solution. I'll close the pull request. Cheers, David

**Comment by dagewa** [comment]
Hi Billy, just checking, are you committing these changes? I think the reciprocal_lattice_viewer changes can go immediately. I guess you might be holding off making the wxtbx change while gearing up for a release?

**Comment by bkpoon** [comment]
Hi David,

Yes, I can check in the changes. It should be done some time today. I'm just double checking the other GUIs that use the SettingsPanel class. Can you check dials.geometry_viewer? I'm not sure how to use that viewer. Thanks!

**Comment by bkpoon** [comment]
I just checked in the changes. The other GUIs, including dials.geometry_viewer, look fine to me.

**Comment by dagewa** [comment]
Thanks Billy. Sorry, I didn't find time to check today, but as you've done so I'll close this.
