### ISSUE TITLE
Installation fails on CentOS 7

### ISSUE THREAD

**Issue by schuerjp1** [cctbx/cctbx_project#517]
Hello Everyone. This is Jon Schuermann at NE-CAT. It has been a while since I have seen you all and I am not sure what everyone is working on now.

 I am trying to install CCTBX on CentOS7 for the purpose of updating our Apache Distl servers. When I try in the install using bootstrap.py I follow Graeme's instructions in the "apache_install_dials.csh" file by first running "python bootstrap.py  --builder=dials hot update" which works fine. Then I run the "python bootstrap.py --nproc=42 base build" and it gets down to building some DXTBX Eiger files and crashes complaining about cannot find -ltiff? It looks like in lib/dxtbx_ext.so, lib/dxtbx_format_image_ext.so, and lib/dxtbx_format_nexus_ext.so. Is there someone specific I should email the traceback or are you familiar with this error? 

Thanks,
  Jon

**Comment by bkpoon** [comment]
Hi Jon,

The "base" step should be building `libtiff` as one of the dependencies. We are still building "base" everyday for CentOS 7, so it should be compiling `dxtbx` successfully. You can see yesterday's log for the ["base" step](https://dev.azure.com/cctbx/3d754415-9516-43fb-8e21-e1fae873ee5e/_apis/build/builds/8287/logs/88) and ["build" step](https://dev.azure.com/cctbx/3d754415-9516-43fb-8e21-e1fae873ee5e/_apis/build/builds/8287/logs/115). Can you provide your log output? There should also compilation output for each dependency in the "base_tmp" directory.

Also, if you want Python 3, you will have to migrate to using `conda` since compiling all the dependencies for each version of Python for multiple operating systems would be too cumbersome to maintain. Essentially, `conda` is a general package management system in user space. You can build `cctbx` with `conda` by adding `--use-conda` to your second command.
```
python bootstrap base build --nproc=42 --use-conda
```
For Python 3, you can choose the Python version with the `--python` flag and the Python version (without the ".") as the argument. For Python 3.8, the command would be
```
python bootstrap base build --nproc=42 --use-conda --python 38
```
Are you building `dials` as well?
It is also possible to build with any `conda` environment, so let me know if you want to do that. Thanks!

**Comment by schuerjp1** [comment]
Hi Billy,

    You are correct the issue was with building base. I had originally launched "python bootstrap.py --with-python=..." and it started to update the modules in the existing python. It got to numpy, uninstalled the existing version, updated to new version, then checked for existence of the egg file for the old version that had been uninstalled and failed. I manually checked python to make sure "import numpy" worked then I went back and reran the bootstrap.py command and it went straight into building CCTBX because it defaults to skipping base build if it exists. I assumed it had updated/installed everything but it had not. I reran bootstrap now using the "--force-base-build" option which finished all the rest of the dependencies that it had skipped previously, and built CCTBX fine. You might want to run a check for the dependencies before skipping the base install if it exists. 

Thanks for the help,
    Jon
