### ISSUE TITLE
phil parameter disambiguation

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#8]
(originally reported in dials/dials/issues/265)

I assert we can do better than
```
Sorry: Ambiguous parameter definition: global_threshold = 20.0
Best matches:
  spotfinder.threshold.xds.global_threshold
  spotfinder.threshold.helen.global_threshold
```

Suggest distinguishing two levels of ambiguity.
* If one of the matches has a minimum expert_level, ie which is lower than that of all alternative matches, then print a warning: ```You said xx. I think you meant 'banana' and I will proceed under this assumption.```.
* If two or more matches have the same minimum expert_levels, fail. Potentially list the more likely options first.

**Comment by olegsobolev** [comment]
Sorry for delayed comment.
Given that much of the parameters in cctbx and Phenix has rather arbitrary expert level I would not use it for this matter. In presented example I assume those two parameters will also have the same expert level.
In fact, I feel much more safe to leave it like it is now, i.e. make user actively pick and type proper parameter.

**Comment by pafonine** [comment]
> Given that much of the parameters in cctbx and Phenix has rather 
> arbitrary expert level

Can't resist from commenting on this part. Expert level attributes are 
often "arbitrary" mostly because respective developers didn't both to 
spend a second and put a meaningful values. So this occasional 
arbitrariness is not by design but rather by failure of some individuals.

When it comes to GUI, expert level is extremely important.

Pavel

**Comment by graeme-winter** [comment]
Why don't we then say that the expert level *is* meaningful and then repair places where it is not

This is also a bedrock of dials ui design so I think we should push towards it. 

Cheers Graeme

**Comment by pafonine** [comment]
Can't agree more! The trouble is that expert level was introduced a 
while ago and since then there were generations of postdocs doing 1-3 
year "postdoc quality" jobs, which included producing lots of codes and 
also not paying much attention to expert level (and their mentors 
apparently failed to do a proper QA too!). So... agreeing it *is* 
meaningful is good and easy. Fixing it everywhere at once is doable but 
much less easy. I guess a realistic scenario is to do it gradually. Say 
if by chance you run into a piece of code and see expert level - just 
try to fix it. To do this though most of the time you will need to know 
the code and what it does (to be able to scale "expertness" level of a 
given parameter).

Pavel

**Comment by rjgildea** [comment]
This potential feature could be made optional in the phil parser (default = current behaviour) which would mean we could turn it on in specific cases (e.g. dials).

**Comment by Anthchirp** [comment]
I feel that this is descending into a bikeshed argument. The proposed solution is [pareto efficient](https://en.wikipedia.org/wiki/Pareto_efficiency) - users only get either exactly the same or a strictly better result than what they would otherwise get. It should therefore not be optional.
