### ISSUE TITLE
Update conda version to 3.8.15 on anaconda.org 

### ISSUE THREAD

**Issue by c3ivodujmovic** [cctbx/cctbx_project#813]
I think you guys have been updating python version on repo.anaconda.com , like https://anaconda.org/cctbx202008/python 
Since there is a new version with CVE fixes, I was wondering if you plan to update it? :) https://www.python.org/downloads/release/python-3815/ 

PS I am guessing you have a CI flow that does it after some testing, so hope to benefit. Thanks :)

**Comment by bkpoon** [comment]
That version is just a copy of the one from the `conda-forge` channel (https://anaconda.org/conda-forge/python). We copy that so that we have a version that is more easily found for our explicit conda environments (each version can have multiple builds and we track one at any given time). We do update our explicit environments, but we rely on `conda-forge` for updating these dependencies. I would follow the `conda-forge` channel for updated versions.

We do test our `cctbx-base` conda packages on our CI every day by running a subset of tests on whatever environment is solved for that day with packages from the `conda-forge` channel.

**Comment by bkpoon** [comment]
The CVE fixes should be in the latest versions from `conda-forge`.

https://anaconda.org/conda-forge/python

If one of the CVEs in question is about converting long strings to integers, the `conda-forge` discussion with links to the Python discussions is here (https://github.com/conda-forge/python-feedstock/pull/579).
